/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Config } from "./models/model";
export namespace Components {
    interface CashReceipt {
        /**
          * The first name
         */
        "config": Config;
    }
    interface CompanyInfo {
        /**
          * The first name
         */
        "config": Config;
    }
    interface CustomerInfo {
        /**
          * The first name
         */
        "config": Config;
    }
    interface InvoiceInfo {
        /**
          * The first name
         */
        "config": Config;
    }
    interface ItemsInfo {
        /**
          * The first name
         */
        "config": Config;
    }
    interface TotalInfo {
        /**
          * The first name
         */
        "config": Config;
    }
}
declare global {
    interface HTMLCashReceiptElement extends Components.CashReceipt, HTMLStencilElement {
    }
    var HTMLCashReceiptElement: {
        prototype: HTMLCashReceiptElement;
        new (): HTMLCashReceiptElement;
    };
    interface HTMLCompanyInfoElement extends Components.CompanyInfo, HTMLStencilElement {
    }
    var HTMLCompanyInfoElement: {
        prototype: HTMLCompanyInfoElement;
        new (): HTMLCompanyInfoElement;
    };
    interface HTMLCustomerInfoElement extends Components.CustomerInfo, HTMLStencilElement {
    }
    var HTMLCustomerInfoElement: {
        prototype: HTMLCustomerInfoElement;
        new (): HTMLCustomerInfoElement;
    };
    interface HTMLInvoiceInfoElement extends Components.InvoiceInfo, HTMLStencilElement {
    }
    var HTMLInvoiceInfoElement: {
        prototype: HTMLInvoiceInfoElement;
        new (): HTMLInvoiceInfoElement;
    };
    interface HTMLItemsInfoElement extends Components.ItemsInfo, HTMLStencilElement {
    }
    var HTMLItemsInfoElement: {
        prototype: HTMLItemsInfoElement;
        new (): HTMLItemsInfoElement;
    };
    interface HTMLTotalInfoElement extends Components.TotalInfo, HTMLStencilElement {
    }
    var HTMLTotalInfoElement: {
        prototype: HTMLTotalInfoElement;
        new (): HTMLTotalInfoElement;
    };
    interface HTMLElementTagNameMap {
        "cash-receipt": HTMLCashReceiptElement;
        "company-info": HTMLCompanyInfoElement;
        "customer-info": HTMLCustomerInfoElement;
        "invoice-info": HTMLInvoiceInfoElement;
        "items-info": HTMLItemsInfoElement;
        "total-info": HTMLTotalInfoElement;
    }
}
declare namespace LocalJSX {
    interface CashReceipt {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface CompanyInfo {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface CustomerInfo {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface InvoiceInfo {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface ItemsInfo {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface TotalInfo {
        /**
          * The first name
         */
        "config"?: Config;
    }
    interface IntrinsicElements {
        "cash-receipt": CashReceipt;
        "company-info": CompanyInfo;
        "customer-info": CustomerInfo;
        "invoice-info": InvoiceInfo;
        "items-info": ItemsInfo;
        "total-info": TotalInfo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cash-receipt": LocalJSX.CashReceipt & JSXBase.HTMLAttributes<HTMLCashReceiptElement>;
            "company-info": LocalJSX.CompanyInfo & JSXBase.HTMLAttributes<HTMLCompanyInfoElement>;
            "customer-info": LocalJSX.CustomerInfo & JSXBase.HTMLAttributes<HTMLCustomerInfoElement>;
            "invoice-info": LocalJSX.InvoiceInfo & JSXBase.HTMLAttributes<HTMLInvoiceInfoElement>;
            "items-info": LocalJSX.ItemsInfo & JSXBase.HTMLAttributes<HTMLItemsInfoElement>;
            "total-info": LocalJSX.TotalInfo & JSXBase.HTMLAttributes<HTMLTotalInfoElement>;
        }
    }
}
